### ISSUE TITLE
Multi Language Support Is Not Working.

### ISSUE THREAD

**Issue by codesankalp** [freshlybuiltongithub/freshlybuiltimagebol#21]
### Issue Detail
While __converting__ audio into different languages like `(Luxembourgish)` g-trans is unable to translate it and gives an error.
__So Please Solve it.__

### ToDo
 - [ ] Add only those languages which are supported by G-Trans

**Comment by vishal2612200** [comment]
Can you please explain your error furthermore? It will be helpful for us to resolve your issue.

**Comment by codesankalp** [comment]
There are more languages added in the package of freshlybuilt but many of them are not supported by gtts.

**Comment by vishal2612200** [comment]
This issue has been resolved with the latest version. If you find it again we can reopen this issue.
